# -*- coding: utf-8 -*-
"""Task - 04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178Xzfj65hQ59Dao6vCbs5Fshi42FNuB7
"""

!pip install fpdf2

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
from fpdf import FPDF  # Now this will work

try:
    url = "https://raw.githubusercontent.com/plotly/datasets/master/US_car_accidents.csv"
    accidents = pd.read_csv(url)
    print("Successfully loaded US Accident Data")
except:
    print("Couldn't download dataset, using sample data")
    accidents = pd.DataFrame({
        'date': pd.date_range('2023-01-01', periods=500),
        'weather': ['Clear']*300 + ['Rain']*100 + ['Snow']*50 + ['Fog']*50,
        'severity': [2]*200 + [3]*150 + [1]*100 + [4]*50,
        'city': ['New York']*150 + ['Chicago']*150 + ['Los Angeles']*200
    })

accidents['date'] = pd.to_datetime(accidents['date'])
accidents['hour'] = accidents['date'].dt.hour
accidents['day_of_week'] = accidents['date'].dt.day_name()
accidents['month'] = accidents['date'].dt.month_name()

plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1)
sns.countplot(x='hour', data=accidents, palette='coolwarm')
plt.title("By Hour")

plt.subplot(1, 3, 2)
sns.countplot(x='day_of_week', data=accidents,
             order=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
             palette='viridis')
plt.title("By Weekday")
plt.xticks(rotation=45)

plt.subplot(1, 3, 3)
sns.countplot(x='month', data=accidents,
             order=['January','February','March','April','May','June',
                    'July','August','September','October','November','December'],
             palette='plasma')
plt.title("By Month")
plt.xticks(rotation=45)

plt.tight_layout()
plt.savefig('time_analysis.png')
plt.show()

plt.figure(figsize=(8, 5))
sns.countplot(y='weather', data=accidents,
             order=accidents['weather'].value_counts().index,
             palette='winter')
plt.title("Weather Conditions During Accidents")
plt.savefig('weather_analysis.png')
plt.show()

plt.figure(figsize=(8, 5))
sns.countplot(x='severity', data=accidents, palette='magma')
plt.title("Accident Severity Distribution")
plt.savefig('severity_analysis.png')
plt.show()

pdf = FPDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 16)
pdf.cell(0, 10, 'US Traffic Accident Analysis', 0, 1, 'C')

pdf.set_font('Arial', '', 12)
pdf.ln(10)
pdf.cell(0, 10, 'Time Patterns:', 0, 1)
pdf.image('time_analysis.png', x=10, w=190)

pdf.ln(5)
pdf.cell(0, 10, 'Weather Conditions:', 0, 1)
pdf.image('weather_analysis.png', x=10, w=190)

pdf.ln(5)
pdf.cell(0, 10, 'Accident Severity:', 0, 1)
pdf.image('severity_analysis.png', x=10, w=190)

pdf.output('accident_report.pdf')
files.download('accident_report.pdf')

print("Report generated and downloaded as accident_report.pdf")